name = "Cobblingcolors"
author = "Scarlett"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e0335f2d5faf56a55d07b69adf7be4de179645df6d72dd85ee3d0d539d7adaa4"

[versions]
fabric = "0.16.14"
minecraft = "1.21.1"
